name: Med comfort workflow

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install flake8 isort pytest pytest-django pytest-cov
          pip install -r med_comfort/requirements.txt

      - name: Test with isort
        run: |
          cd med_comfort/
          isort --check-only ./

      - name: Test with flake8
        run: |
          cd med_comfort/
          flake8 ./

      - name: Test with pytest
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          pytest med_comfort/ --cov --cov-report=xml --cov-fail-under=80

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  send_message:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: The med_comfort deployment has been successfully completed!